version: '3.8'

services:
  app:
    build: .
    container_name: gofiber_app
    ports:
      - 8080:8080
    volumes:
      - .:/app/cmd
    restart: always

  psql_db:
    image: postgres:latest
    container_name: psql_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gofiber_db
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  psql_data:
